SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

VIEWPORT_WIDTH = 960
VIEWPORT_HEIGHT = 720

VIEWPORT_OFFSET_X = 0
VIEWPORT_OFFSET_Y = 0

def viewport_coord(x, y):
    #print (round(min(x * (VIEWPORT_WIDTH-1), VIEWPORT_WIDTH)), round(min(y * (VIEWPORT_WIDTH-1), VIEWPORT_HEIGHT)))
    return round(min(x * (VIEWPORT_WIDTH-1), VIEWPORT_WIDTH)), round(min(y * (VIEWPORT_WIDTH-1), VIEWPORT_HEIGHT))
